import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { Clapperboard, Play, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Genre {
    id: number;
    name: string;
}

async function fetchGenres(): Promise<Genre[]> {
    try {
        const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
            headers: {
                Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
            },
        });
        const data = await res.json();
        return data.genres || []; 
    } catch (error) {
        console.error("Fetch Genres Error:", error);
        return [];
    }
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const genres = await fetchGenres();

    async function searchMovie(formData: FormData) {
        "use server";
        const q = formData.get('q');
        if (q) redirect(`/search?q=${q}`);
    }

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header className="p-4 border-b flex justify-between items-center">
                    <h1 className="font-bold text-2xl flex gap-2 items-center">
                        <Clapperboard />
                        Next Movie
                    </h1>
                    <form className="flex gap-1" action={searchMovie}>
                        <Input placeholder="Search" name="q" />
                        <Button type="submit">
                            <Search className="w-4 h-4" />
                        </Button>
                    </form>
                </header>
                <main className="flex min-h-screen">
                    <nav className="w-64 p-4 border-r flex flex-col gap-2 overflow-y-auto max-h-screen sticky top-0">
                        <Button variant="outline" asChild>
                            <Link href="/" className="flex justify-start gap-2">
                                <Play className="w-4 h-4" />
                                All Movies
                            </Link>
                        </Button>
                        <p className="text-xs font-semibold text-gray-500 px-2 mt-4 mb-1 uppercase">Genres</p>
                        {genres.map((genre: Genre) => (
                            <Button
                                key={genre.id}
                                variant="ghost"
                                className="w-full justify-start gap-2"
                                asChild
                            >
                                <Link href={`/genre/${genre.name}/${genre.id}`}>
                                    <Play className="w-4 h-4" />
                                    {genre.name}
                                </Link>
                            </Button>
                        ))}
                    </nav>
                    <section className="flex-1 p-6">{children}</section>
                </main>
            </body>
        </html>
    );
}
